quarkus.http.port=8080

# Configuracion del RestClient
quarkus.rest-client.consulta-client.url=http://bh-query-datagrid-ksvc-v1.cachebh.svc.cluster.local
#quarkus.rest-client.consulta-client.url=https://bh-query-datagrid-ksvc-cachebh.apps.osft4-rhaf.colsanitas.com

# Configuracion TLS para el RestClient
#quarkus.native.resources.includes=truststore.p12

#quarkus.tls.camel-tls.trust-store.p12.path=truststore.p12
#quarkus.tls.camel-tls.trust-store.p12.password=password
#quarkus.rest-client.consulta-client.tls-configuration-name=camel-tls



# Optimizacion de memoria y threads para 100 TPS
quarkus.thread-pool.core-threads=50
quarkus.thread-pool.max-threads=200
quarkus.vertx.event-loops-pool-size=8

# Configuracion HTTP reactiva
quarkus.http.enable-compression=true
quarkus.http.limits.max-body-size=10M

