####
# Dockerfile multi-stage para compilar y ejecutar Quarkus en modo nativo
#
# Build del contenedor:
# docker build -f src/main/docker/Dockerfile.native.multistage -t arquetipo-quarkus:native .
#
# Ejecutar el contenedor:
# docker run -i --rm -p 8082:8082 arquetipo-quarkus:native
###
# Stage 1: Build nativo
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.2.0:go-offline
COPY --chown=quarkus:quarkus src /code/src
# Si el truststore está en resources, ya se incluirá automáticamente con quarkus.native.resources.includes
RUN ./mvnw package -Dnative

# Stage 2: Runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY --from=build --chown=1001:root /code/target/*-runner /work/application
# El truststore se incluirá automáticamente en el ejecutable nativo si está en src/main/resources
# y está configurado en application.properties con quarkus.native.resources.includes

EXPOSE 8082
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]

